# Build frontend
FROM node:20 AS build

ENV REGION=asia-east1
ENV ZONE=asia-east1-b

WORKDIR /app
COPY service/frontend/package*.json /app/
RUN npm install
COPY service/frontend /app
RUN npm run build

# Serve with Nginx
FROM nginx:alpine
COPY service/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html