FROM python:3.13-slim

RUN apt update && \
    apt-get install -y --no-install-recommends \
        make \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY service/backend/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt && pip freeze

COPY service/backend /app
