services:
  backend:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile-backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
    working_dir: /app
    command: python3 run.py
    networks:
      - app-network

  frontend:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile-frontend
    ports:
      - "5003:80"
    command: nginx -g 'daemon off;'
    networks:
      - app-network

networks:
  app-network:
