FROM python:3.12-slim

ENV REGION=asia-east1
ENV ZONE=asia-east1-b

RUN apt update && \
    apt install -y --no-install-recommends \
        make \
        git \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY service/backend/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt && pip freeze

COPY service/backend /app
