FROM node:20 AS build

WORKDIR /app
COPY service/frontend /app
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

COPY service/frontend/nginx.conf /etc/nginx/conf.d/default.conf
